// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMKOTU9VcRNJhLZONOahLm-_9lLQxSMRQ',
    appId: '1:531227693637:web:1798556bbd128972d4092c',
    messagingSenderId: '531227693637',
    projectId: 'shopping-app-bdb9f',
    authDomain: 'shopping-app-bdb9f.firebaseapp.com',
    storageBucket: 'shopping-app-bdb9f.appspot.com',
    measurementId: 'G-4V00EC6TVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNuztSbaSji8Jqkbdhd8V4b_6Vx98TGRA',
    appId: '1:531227693637:android:fb2c17c460cf96c8d4092c',
    messagingSenderId: '531227693637',
    projectId: 'shopping-app-bdb9f',
    storageBucket: 'shopping-app-bdb9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCREtwiL4IbX_-oX4hGs91_KK1lU35HpD4',
    appId: '1:531227693637:ios:47ac5398a6abc87bd4092c',
    messagingSenderId: '531227693637',
    projectId: 'shopping-app-bdb9f',
    storageBucket: 'shopping-app-bdb9f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCREtwiL4IbX_-oX4hGs91_KK1lU35HpD4',
    appId: '1:531227693637:ios:47ac5398a6abc87bd4092c',
    messagingSenderId: '531227693637',
    projectId: 'shopping-app-bdb9f',
    storageBucket: 'shopping-app-bdb9f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMKOTU9VcRNJhLZONOahLm-_9lLQxSMRQ',
    appId: '1:531227693637:web:1798556bbd128972d4092c',
    messagingSenderId: '531227693637',
    projectId: 'shopping-app-bdb9f',
    authDomain: 'shopping-app-bdb9f.firebaseapp.com',
    storageBucket: 'shopping-app-bdb9f.appspot.com',
    measurementId: 'G-4V00EC6TVF',
  );

}